AllCops:
  TargetRubyVersion: 2.5.3

require:
  - rubocop-rspec
  - rubocop-performance

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 19

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit