sudo: true

env:
  global:
  - SAUCE_USERNAME=sauce_examples

jobs:
  include:
    - stage: "Run All Tests"
      python: "3.6"
      jdk: "openjdk8"
      rvm: "2.4"
      before_install: export | grep SAUCE_
      script: make run_all_tests
